apiVersion: v2
name: mediarr
description: A Helm chart for the *arr suite (Prowlarr, Radarr, Sonarr, Lidarr, Bazarr, qBittorrent, FlareSolverr).
type: application
version: 0.5.0
keywords:
  - mediarr
  - servarr
  - prowlarr
  - flaresolverr
  - radarr
  - sonarr
  - lidarr
  - bazarr
  - qbittorrent
maintainers:
  - name: trankimtung
dependencies:
  - name: common
    version: "0.4.1"
    repository: "oci://ghcr.io/trankimtung/helm-charts"
