{{- include "paperless-ngx.validate" . }}
{{- $enabled := dict }}
{{- range $name, $comp := .Values.components }}
{{- if ne $comp.enabled false }}
{{- $_ := set $enabled $name $comp }}
{{- end }}
{{- end }}
{{- include "common.components" (dict "ctx" . "components" $enabled) }}
