apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}-ha-default-config
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data:
  configuration.yaml: |
    {{- .Values.homeAssistant.defaultConfig | nindent 4 }}
