apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
    {{- with .Values.homeAssistant.service.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.homeAssistant.service.type }}
  ports:
    - name: http
      port: 8123
      targetPort: http
      protocol: TCP
  selector:
    {{- include "home-assistant.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: home-assistant
