apiVersion: v2
name: home-assistant
description: A Helm chart for Home Assistant, with Mosquitto MQTT and Zigbee2MQTT
type: application
version: 0.2.0
# renovate: datasource=docker depName=ghcr.io/home-assistant/home-assistant
appVersion: "2026.8.1"
keywords:
  - home-assistant
  - mqtt
  - zigbee2mqtt
  - automation
  - iot
maintainers:
  - name: trankimtung
