apiVersion: v2
name: searxng
description: A Helm chart for SearXNG - a privacy-respecting metasearch engine
icon: https://raw.githubusercontent.com/searxng/searxng/master/client/simple/src/brand/searxng.svg
type: application
version: 0.2.1
# renovate: datasource=docker depName=searxng/searxng
appVersion: 2026.9.12-d4f00d15d
keywords:
  - searxng
  - search
  - metasearch
maintainers:
  - name: trankimtung
dependencies:
  - name: common
    version: 0.4.1
    repository: oci://ghcr.io/trankimtung/helm-charts
